version: '3.1'

services:
        db:
                image: mariadb:10.3
                restart: always
                volumes:
                        - ${ROOT}/files/db:/var/lib/mysql
                        - ${ROOT}/etc/secrets-db:/secrets-db
                environment:
                        MYSQL_ROOT_PASSWORD_FILE: /secrets-db/dbadminpass
                        MYSQL_DATABASE_FILE: /secrets-db/db
                        MYSQL_USER_FILE: /secrets-db/dbuser
                        MYSQL_PASSWORD_FILE: /secrets-db/dbuserpass

        w1:
                depends_on:
                        - db
                image: ruiseabra/wordpress
                restart: always
                volumes:
                        - ${ROOT}/files/wordpress:/var/www/html
                        - ${ROOT}/etc/wp-config.php:/var/www/html/wp-config.php
        w2:
                depends_on:
                        - db
                image: ruiseabra/wordpress
                restart: always
                volumes:
                        - ${ROOT}/files/wordpress:/var/www/html
                        - ${ROOT}/etc/wp-config.php:/var/www/html/wp-config.php

        lb:
                image: haproxy:1.8
                ports:
                        - 8000:80
                restart: always
                volumes:
                        - ${ROOT}/etc/haproxy:/usr/local/etc/haproxy
